// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqC32xARdKjitUI4EbkdGgn5en08l2FA',
    appId: '1:64841492660:web:911d126dad150877f08fe1',
    messagingSenderId: '64841492660',
    projectId: 'email-password-authentic-282d7',
    authDomain: 'email-password-authentic-282d7.firebaseapp.com',
    storageBucket: 'email-password-authentic-282d7.appspot.com',
    measurementId: 'G-5FFY9PD7N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPgnzDVNQSxAne3QxQ8DSgKPs22h4_NE',
    appId: '1:64841492660:android:7f3c2e1fa85e4e4af08fe1',
    messagingSenderId: '64841492660',
    projectId: 'email-password-authentic-282d7',
    storageBucket: 'email-password-authentic-282d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgmGoeReca6IKO-0jDqeTIPQJJ3xkTv8',
    appId: '1:64841492660:ios:e2ca31d495fa4784f08fe1',
    messagingSenderId: '64841492660',
    projectId: 'email-password-authentic-282d7',
    storageBucket: 'email-password-authentic-282d7.appspot.com',
    iosClientId: '64841492660-q5i42p0eavs2tofvrhscqimgnulic3fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailPasswordAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjgmGoeReca6IKO-0jDqeTIPQJJ3xkTv8',
    appId: '1:64841492660:ios:e2ca31d495fa4784f08fe1',
    messagingSenderId: '64841492660',
    projectId: 'email-password-authentic-282d7',
    storageBucket: 'email-password-authentic-282d7.appspot.com',
    iosClientId: '64841492660-q5i42p0eavs2tofvrhscqimgnulic3fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailPasswordAuthentication',
  );
}
